Handle multifile in pget wrapper

diff --git a/src/pget b/src/pget
--- a/src/pget
+++ b/src/pget
@@ -4,31 +4,15 @@
 
 set -euo pipefail
 
-PGET_BIN="$MONOBASE_PREFIX/bin/pget-bin"
-PROC_FILE="/srv/r8/fuse-rpc/proc/pget"
+PGET_BIN="${PGET_BIN:-${MONOBASE_PREFIX:-/srv/r8/monobase}/bin/pget-bin}"
+FUSE_MOUNT="${FUSE_MOUNT:-/srv/r8/fuse-rpc}"
 
-# No FUSE proc file, use vanilla PGET
-if [ ! -f "$PROC_FILE" ]; then
-    exec "$PGET_BIN" "$@"
-fi
+PROC_FILE="$FUSE_MOUNT/proc/pget"
 
-url=''
-dst=''
-extract=0
-unknown=0
-for arg in "$@"; do
-    case "$arg" in
-        http://*|https://*) url="$arg" ;;
-        -x|--extract) extract=1 ;;
-        --*|-*) unknown=1 ;;
-        *) dst="$arg" ;;
-    esac
-done
+fuse_pget() {
+    url="$1"
+    dst="$2"
 
-# Fail to parse arguments, use vanilla PGET
-if [ "$unknown" -eq 1 ] || [ -z "$url" ] || [ -z "$dst" ]; then
-    exec "$PGET_BIN" "$@"
-else
     # Finger print object name with URL, size, ETag, and last modified
     echo "$(date --iso-8601=seconds --utc) pget $*"
     out="$(curl -fsSL -I "$url" | grep -i '^\(content-length:\|etag:\|last-modified:\)')"
@@ -43,21 +27,44 @@ else
     name="pget/sha256/$sha256"
     size="$(echo "$fingerprint" | grep -ioP '(?<=^content-length: )[0-9]+')"
 
-    echo "FUSE object: $name"
-    echo "Fingerprint:"
-    echo "$fingerprint"
+    if [[ $size -le 1048576 ]]; then
+        # Fallback for small files
+        "$PGET_BIN" "$@"
+    else
+        # Request file from FUSE
+        echo "{\"name\":\"$name\",\"size\":$size,\"url\":\"$url\"}" > "$PROC_FILE"
 
-
-    # Request file from FUSE
-    echo "{\"name\":\"$name\",\"size\":$size,\"url\":\"$url\"}" > "$PROC_FILE"
-
-    if [ "$extract" -eq 0 ]; then
         # Symlink file to destination
         mkdir -p "$(dirname "$dst")"
-        ln -sf "/srv/r8/fuse-rpc/$name" "$dst"
-    else
-        # Extract tarball to destination
-        mkdir -p "$dst"
-        tar -xf "/srv/r8/fuse-rpc/$name" -C "$dst"
+        ln -sf "$FUSE_MOUNT/$name" "$dst"
     fi
+}
+
+if [ ! -f "$PROC_FILE" ]; then
+    # No FUSE proc file, fallback
+    exec "$PGET_BIN" "$@"
+elif [[ $# -ne 2 ]]; then
+    # Fallback
+    exec "$PGET_BIN" "$@"
+elif [[ "$1" == http://* ]] || [[ "$1" == https://* ]]; then
+    # pget <url> <dst>
+    fuse_pget "$@"
+elif [[ "$1" == multifile ]]; then
+    in="$2"
+    if [[ "$2" == - ]]; then
+        in=/dev/stdin
+    fi
+    while read -r line; do
+        [[ -n "$line" ]] || continue
+        url="${line// */}"
+        dst="${line//* /}"
+        if [[ "$line" != "$url $dst" ]]; then
+            echo "Error: error parsing manifest: invalid line format \`$line\`"
+            exit 1
+        fi
+        fuse_pget "$url" "$dst"
+    done < "$in"
+else
+    # Fallback
+    exec "$PGET_BIN" "$@"
 fi
